version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq3"
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres:13
    container_name: pgdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=zaq1@WSX # replace with your secret password
    volumes:
      - postgres:/usr/local/pgsql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: marcin_krysinski@outlook.com
      PGADMIN_DEFAULT_PASSWORD: zaq1@WSX

volumes:
  postgres:
